runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT ecommerce.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
# the secret key used for the Django app (from ecommerce/settings.py)
  SECRET_KEY: '@!-)jwmuzh8btr380g61=g+#&zzei&dz2(&=xbvxztady)_p(r' 
  DEBUG: 'False' # always False for deployment
  
# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  DB_HOST: '/cloudsql/august-jigsaw-230918:us-central1:vriksh-db'
  DB_PORT: '5432' # PostgreSQL port
  DB_NAME: 'vriksh-db'
  DB_USER: 'ravitejajasti' # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: 'laddu123'
  
  STATIC_URL: 'https://storage.googleapis.com/vriksh/static/' # this is the url that you sync static files to
  
handlers:
- url: /static
  static_dir: static

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: august-jigsaw-230918:us-central1:vriksh-db 

runtime_config:
  python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4