branch-defaults:
  default:
    environment: Vriksh-env-1
environment-defaults:
  Vriksh-env-1:
    branch: null
    repository: null
global:
  application_name: vriksh
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.8.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
