# Generated by Django 2.1.4 on 2019-05-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20190114_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
