# Generated by Django 2.1.4 on 2019-02-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190201_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img/profiles/%Y/%m/%d'),
        ),
    ]
