# Generated by Django 2.1.4 on 2019-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='img/vriksh.svg', null=True, upload_to='avatars', verbose_name='Upload Image'),
        ),
    ]
