# Generated by Django 2.2.6 on 2019-10-19 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('allow_annon', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('discount', models.IntegerField(default=39.99, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('low_maintenance', models.BooleanField(default=False)),
                ('medicinal', models.BooleanField(default=False)),
                ('air_purifier', models.BooleanField(default=False)),
                ('flowering', models.BooleanField(default=False)),
                ('fruit_plant', models.BooleanField(default=False)),
                ('insect_repllenet', models.BooleanField(default=False)),
                ('holy', models.BooleanField(default=False)),
                ('cactus_n_succ', models.BooleanField(default=False)),
                ('creepers', models.BooleanField(default=False)),
                ('herbs', models.BooleanField(default=False)),
                ('indoor', models.BooleanField(default=False)),
                ('miniatures', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=False)),
                ('seasonal', models.BooleanField(default=False)),
                ('ferns', models.BooleanField(default=False)),
                ('office', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(to='products.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'), upload_to=products.models.upload_product_file_loc)),
                ('free', models.BooleanField(default=False)),
                ('user_required', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
