# Generated by Django 2.1.4 on 2019-01-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product'),
        ),
    ]
