# Generated by Django 2.1.4 on 2019-02-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190114_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
