# Generated by Django 2.1.4 on 2019-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_low_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='air_purifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cactus_n_succ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='creepers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ferns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='flowering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fruit_plant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='herbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='holy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='insect_repllenet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='medicinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='miniatures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal',
            field=models.BooleanField(default=False),
        ),
    ]
